<html>
<head>
    <title>This Email generated by www.codechief.org</title>
</head>
<body>
    
    <div>  
    <label> Name: {{ $name }} </label>
    <label> Phone: {{ $phone }} </label>
    <label>  email: {{ $email }} </label>
    <label>  subject: {{ $subject }} </label>
    <label> message: {{ $message1 }} </label>
           
      </div>

<!-- final -->
<!DOCTYPE html>
<html>
    <style>
                span {
                width: 100%;
                padding: 12px 20px;
                margin: 8px 0;
                display: inline-block;
                border: 1px solid #ccc;
                border-radius: 4px;
                box-sizing: border-box;
                }

            

                

                div {
                border-radius: 5px;
                background-color: #f2f2f2;
                padding: 20px;
                }
    </style>
<body>

<h3> customer </h3>

<div>
  <form >
     <label for="fname">First Name:</label>
     <span> {{ $name }} </span>
    
     <label >Phone number</label>
     <span> {{ $phone }} </span>

     <label >Email Adress</label>
     <span> {{ $email }} </span>
     
     <label >Subject</label>
     <span> {{ $subject }} </span>
     <label >Message</label>
     <span> {{ $message1}} </span>
    
  
  
  </form>
</div>

</body>
</html>



</body>
</html> 